openapi: 3.0.0
info:
  title: Ganxue Server API
  description: Ganxue Server API for secure user deletion functionality.
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/auth'
paths:
  /delete-account:
    delete:
      summary: 删除当前用户账户
      description: 当前登录用户删除自己的账户，需要身份验证。
      operationId: deleteCurrentUser
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  format: password
                  description: 用户密码用于确认身份
                  example: userpassword123
              required:
                - password
      responses:
        '200':
          description: 账户删除成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 账户删除成功
        '400':
          description: 请求错误，如密码错误
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 密码错误
        '401':
          description: 未授权
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 未授权，请重新登录
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 服务器错误
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT